- hostname: "web-front"
  ip: "192.168.50.4"
  box: "ubuntu/trusty64"
  apache: "lide.test.conf"
  synced_folders:
    - src: "/home/etudiant/repogit/lide"
      dest: "/home/vagrant/LIDE"
      type: "symfony" # Permet d'activer la creation automatique des schemas en base avec symfony
      options:
        :create: true
        :owner: www-data
        :group: www-data
        :mount_options: ['dmode=0755', 'fmode=0644']
  provision:
    - "provision/common/common.sh"
    - "provision/apache/apache2.sh"
    - "provision/mariadb/mariadb.sh"
    - "provision/php/php7.2.sh"
    - "provision/misc/misc-web.sh"

- hostname: "web-back"
  ip: "192.168.50.5"
  box: "ubuntu/trusty64"
  docker:
    - "gpp" # Le nom du dockerfile sera le nom de l'image sur le guest
  provision:
    - "provision/common/common.sh"
    - "provision/docker/docker.sh"
    - "provision/apache/apache2.sh"
    - "provision/php/php7.2.sh"
